# Generated by ChatGPT
import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Number",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area_code",
                    models.CharField(
                        db_index=True,
                        help_text="Exactly three digits representing the area code.",
                        max_length=3,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="Exactly seven digits for the local number.",
                        max_length=7,
                    ),
                ),
                (
                    "cost",
                    models.PositiveIntegerField(
                        help_text="Cost in USD cents or dollars as configured."
                    ),
                ),
            ],
            options={"ordering": ["area_code", "phone_number"]},
        ),
        migrations.AddConstraint(
            model_name="number",
            constraint=models.UniqueConstraint(fields=("area_code", "phone_number"), name="unique_area_phone"),
        ),
        migrations.AddIndex(
            model_name="number",
            index=models.Index(fields=["area_code"], name="core_number_area_idx"),
        ),
        migrations.AddIndex(
            model_name="number",
            index=models.Index(fields=["phone_number"], name="core_number_phone_idx"),
        ),
        migrations.AddIndex(
            model_name="number",
            index=models.Index(fields=["area_code", "phone_number"], name="core_number_area_phone_idx"),
        ),
    ]
