name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: phone_numbers
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_ENGINE: postgres
      DATABASE_NAME: phone_numbers
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DJANGO_SECRET_KEY: test-secret
      ALLOWED_HOSTS: localhost
      CORS_ALLOWLIST: https://www.example.com
      DJANGO_DEBUG: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run migrations
        run: |
          python services/api/manage.py migrate --noinput
      - name: Run tests (API)
        env:
          PYTHONPATH: .
        run: |
          pytest --ds=api.settings services/api/tests
      - name: Run tests (Admin)
        env:
          PYTHONPATH: .
        run: |
          pytest --ds=dashboard.settings services/admin/tests
      - name: Build docker images
        run: |
          docker build -t phone-api -f services/api/Dockerfile .
          docker build -t phone-admin -f services/admin/Dockerfile .
